package com.bol.core.dto;
// default package
// Generated 15 Sep, 2019 5:40:40 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Email;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * UserMaster generated by hbm2java
 */
@Entity
@Table(name = "users" /* , catalog = "bol_start" */ ) 
public class Users implements java.io.Serializable,Comparable<Users> {

	private Long id;
	private String mobileNumber;
	private String emailId;
	private String firstName;
	private String lastName;
	private String otp;
	private String password;
	private String deviceId;
	private String os;
	private String profilePicture;
	private String country;
	private String headline;
	private String month;
	private String day;
	private String gst;
	private String adhaarCard;
	private String timlineImage;
	private String  cin;
	private String state;
	private String location;
	private String isFbLogged;
	private String isGoogleLogged;
	private String isLkLogged;
	private String isEmailVerified;
	private String isMobileVerified;
	private Long typeOfUser;
	private String industryName;
	private String isFollowed;
	private String isConnected;
	private int connectionCount;
	private String isPriority;
	private String uid;
	private List<Skills> skill;
	private String bio;
	private Long company_id;
	private String isAuthories;
	private String userRole;
	private String companyName;
	private String compnayLogo;
	private String creationDate;
//	private boolean isActive;
	
	private List<Education> education;
	private List<Experience> experience;
	private List<Accomplishment> accomplishment;
	

	public Users() {
	}

	@JsonIgnore
	@Column(name="creationDate")
	public String getCreationDate() {
		return creationDate;
	}


	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

//    @Column(name="isActive")
//	public boolean isActive() {
//		return isActive;
//	}


//	public void setActive(boolean isActive) {
//		this.isActive = isActive;
//	}


	@Column(name="company_name")
	public String getCompanyName() {
		return companyName;
	}



	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}


    @Column(name="company_logo")
	public String getCompnayLogo() {
		return compnayLogo;
	}



	public void setCompnayLogo(String compnayLogo) {
		this.compnayLogo = compnayLogo;
	}



	@Column(name="user_role")
    public String getUserRole() {
		return userRole;
	}






	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}






	@Column(name="isAuthories")
	public String getIsAuthories() {
		return isAuthories;
	}


	public void setIsAuthories(String isAuthories) {
		this.isAuthories = isAuthories;
	}






	public Users(Long id, String mobileNumber, String emailId, String firstName, String lastName, String otp,
			String password, String deviceId, String os, String profilePicture, String country, String headline,
			String month, String day, String gst, String adhaarCard, String timlineImage, String cin, String state,
			String location, String isFbLogged, String isGoogleLogged, String isLkLogged, String isEmailVerified,
			String isMobileVerified, Long typeOfUser, String industryName, String isFollowed, String isConnected,
			int connectionCount, String isPriority, String uid, List<Skills> skill, String bio, Long company_id,
			List<Education> education, List<Experience> experience, List<Accomplishment> accomplishment) {
		super();
		this.id = id;
		this.mobileNumber = mobileNumber;
		this.emailId = emailId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.otp = otp;
		this.password = password;
		this.deviceId = deviceId;
		this.os = os;
		this.profilePicture = profilePicture;
		this.country = country;
		this.headline = headline;
		this.month = month;
		this.day = day;
		this.gst = gst;
		this.adhaarCard = adhaarCard;
		this.timlineImage = timlineImage;
		this.cin = cin;
		this.state = state;
		this.location = location;
		this.isFbLogged = isFbLogged;
		this.isGoogleLogged = isGoogleLogged;
		this.isLkLogged = isLkLogged;
		this.isEmailVerified = isEmailVerified;
		this.isMobileVerified = isMobileVerified;
		this.typeOfUser = typeOfUser;
		this.industryName = industryName;
		this.isFollowed = isFollowed;
		this.isConnected = isConnected;
		this.connectionCount = connectionCount;
		this.isPriority = isPriority;
		this.uid = uid;
		this.skill = skill;
		this.bio = bio;
		this.company_id = company_id;
		this.education = education;
		this.experience = experience;
		this.accomplishment = accomplishment;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "MOBILE_NUMBER",length = 255)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	
	@Column(name = "EMAIL_ID", length = 100)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "FIRST_NAME",length = 255)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME",length = 255)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	
	@JsonIgnore
	@Column(name = "OTP", length = 10)
	public String getOtp() {
		return this.otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@JsonProperty(access = Access.WRITE_ONLY)
	@Column(name = "PASSWORD", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}


	@JsonIgnore
	@Column(name = "DEVICE_ID", length = 500)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}


	@JsonIgnore
	@Column(name = "OS", length = 100)
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Column(name = "PROFILE_PICTURE",length = 255)
	public String getProfilePicture() {
		return this.profilePicture;
	}

	public void setProfilePicture(String profilePicture) {
		this.profilePicture = profilePicture;
	}

	
	@Column(name="IS_LOGGED_GOOGLE",length = 255)
	public String getIsGoogleLogged() {
		return isGoogleLogged;
	}

	public void setIsGoogleLogged(String isGoogleLogged) {
		this.isGoogleLogged = isGoogleLogged;
	}
	
	@Column(name="is_fb_logged",length = 255)
	public String getIsFbLogged() {
		return isFbLogged;
	}

	public void setIsFbLogged(String isFbLogged) {
		this.isFbLogged = isFbLogged;
	}

	@Column(name="is_lk_logged",length = 255)
	public String getIsLkLogged() {
		return isLkLogged;
	}

	public void setIsLkLogged(String isLkLogged) {
		this.isLkLogged = isLkLogged;
	}

	@Column(name="is_email_verified",length = 255)
	public String getIsEmailVerified() {
		return isEmailVerified;
	}


	public void setIsEmailVerified(String isEmailVerified) {
		this.isEmailVerified = isEmailVerified;
	}

	@Column(name="is_mobile_verified",length = 255)
	public String getIsMobileVerified() {
		return isMobileVerified;
	}

	public void setIsMobileVerified(String isMobileVerified) {
		this.isMobileVerified = isMobileVerified;
	}


	@Column(name="type_of_user")
	public Long getTypeOfUser() {
		return typeOfUser;
	}


	public void setTypeOfUser(Long typeOfUser) {
		this.typeOfUser = typeOfUser;
	}

	


	@Transient
	public List<Skills> getSkill() {
		return skill;
	}

	public void setSkill(List<Skills> skill) {
		this.skill = skill;
	}

	@Column(name="bio",length = 5000)
	public String getBio() {
		return bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	@Transient
	public List<Education> getEducation() {
		return education;
	}

	public void setEducation(List<Education> education) {
		this.education = education;
	}

	@Transient
	public List<Experience> getExperience() {
		return experience;
	}

	public void setExperience(List<Experience> experience) {
		this.experience = experience;
	}

	@Transient
	public List<Accomplishment> getAccomplishment() {
		return accomplishment;
	}

	public void setAccomplishment(List<Accomplishment> accomplishment) {
		this.accomplishment = accomplishment;
	}


	@Column(name="month",length = 255)
	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}
	
	@Column(name="day",length = 255)
	public String getDay() {
		return day;
	}
	public void setDay(String day) {
		this.day = day;
	}

	@Column(name="gst",length = 255)
	public String getGst() {
		return gst;
	}

	public void setGst(String gst) {
		this.gst = gst;
	}

	@Column(name="adhaar_card",length = 255)
	public String getAdhaarCard() {
		return adhaarCard;
	}

	public void setAdhaarCard(String adhaarCard) {
		this.adhaarCard = adhaarCard;
	}

	@Column(name="cin",length = 255)
	public String getCin() {
		return cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name="state",length = 255)
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name="location",length = 255)
	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}



	@Column(name="country",length = 255)
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}


	@Column(name="headline",length = 5000)
	public String getHeadline() {
		return headline;
	}




	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name="timeline_image",length = 255)
	public String getTimlineImage() {
		return timlineImage;
	}

	public void setTimlineImage(String timlineImage) {
		this.timlineImage = timlineImage;
	}




	@Column(name="industry_name",length = 255)
	public String getIndustryName() {
		return industryName;
	}




	public void setIndustryName(String industryName) {
		this.industryName = industryName;
	}



	

	@JsonProperty(access = Access.READ_ONLY)
	@Transient
	public String getIsFollowed() {
		return isFollowed;
	}




	public void setIsFollowed(String isFollowed) {
		this.isFollowed = isFollowed;
	}



	@JsonProperty(access = Access.READ_ONLY)
	@Transient
	public String getIsConnected() {
		return isConnected;
	}




	public void setIsConnected(String isConnected) {
		this.isConnected = isConnected;
	}


	@JsonProperty(access = Access.READ_ONLY)
	@Transient
	public int getConnectionCount() {
		return connectionCount;
	}




	public void setConnectionCount(int connectionCount) {
		this.connectionCount = connectionCount;
	}




	@Column(name="is_priority",length = 255)
	public String getIsPriority() {
		return isPriority;
	}




	public void setIsPriority(String isPriority) {
		this.isPriority = isPriority;
	}


	@Column(name="uid",length = 255)
	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name="company_id")
	public Long getCompany_id() {
		return company_id;
	}




	public void setCompany_id(Long company_id) {
		this.company_id = company_id;
	}




	@Override
	public int compareTo(Users user) {
		// TODO Auto-generated method stub
		return this.userRole.compareTo(user.userRole);
	}

	@Override
	public String toString() {
		return "Users [id=" + id + ", mobileNumber=" + mobileNumber + ", emailId=" + emailId + ", firstName="
				+ firstName + ", lastName=" + lastName + ", otp=" + otp + ", password=" + password + ", deviceId="
				+ deviceId + ", os=" + os + ", profilePicture=" + profilePicture + ", country=" + country
				+ ", headline=" + headline + ", month=" + month + ", day=" + day + ", gst=" + gst + ", adhaarCard="
				+ adhaarCard + ", timlineImage=" + timlineImage + ", cin=" + cin + ", state=" + state + ", location="
				+ location + ", isFbLogged=" + isFbLogged + ", isGoogleLogged=" + isGoogleLogged + ", isLkLogged="
				+ isLkLogged + ", isEmailVerified=" + isEmailVerified + ", isMobileVerified=" + isMobileVerified
				+ ", typeOfUser=" + typeOfUser + ", industryName=" + industryName + ", isFollowed=" + isFollowed
				+ ", isConnected=" + isConnected + ", connectionCount=" + connectionCount + ", isPriority=" + isPriority
				+ ", uid=" + uid + ", skill=" + skill + ", bio=" + bio + ", company_id=" + company_id + ", isAuthories="
				+ isAuthories + ", userRole=" + userRole + ", companyName=" + companyName + ", compnayLogo="
				+ compnayLogo + ", creationDate=" + creationDate + ", education=" + education + ", experience="
				+ experience + ", accomplishment=" + accomplishment + "]";
	}

	
	
	
	
	

	
}
